# is a organization repository ?
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'

# site title
title: VxRail Tech

# github user: your github username
user: VxRailGithub

# issue repository: your issues repository, the issues is the blog content
repository: vxrail.tech

# multi-authors, the user name above is included in
# multi-authors must be separated by ','
# example: author0,author1
authors: VxRailGithub

# token
# token must be separated by '#'
# if your token is 5c31bffc137f44faf7efc4a84da827g7ca2cfeaa
# the token value is 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 6#7959d4d678bea69e5ab609077b314c5b0afef07

# posts per page
perpage: 10